Throw an exception when applying the plugins on gradle < 4.10
Because we use the new configuration avoidance API, Gradle versions
older than 4.10 are not supported. Attempting to use an older version
resulted in a NoSuchMethodError, which does not point to the cause of
the error at all.

Fixes #13